### ISSUE TITLE
cmake error while building project

### ISSUE THREAD

**Issue by dhr999** [juanmanzanero/lion-cpp#1]
Hi, I am trying to build this project to run with "fastest-lap", on Ubuntu 18.04. I am getting this error and I am not able to fix it. I understand it's because of the "GTests" package. I have also attached the error log and the make output log.

Error msg:
```
CMake Error at cmake/get-third-party.cmake:69 (find_package):
  Could not find a package configuration file provided by "GTest" with any of
  the following names:

    GTestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "GTest" to CMAKE_PREFIX_PATH or set
  "GTest_DIR" to a directory containing one of the above files.  If "GTest"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
```
Can you please help me?

[CMakeError.log](https://github.com/juanmanzanero/lion-cpp/files/8630602/CMakeError.log)
[CMakeOutput.log](https://github.com/juanmanzanero/lion-cpp/files/8630603/CMakeOutput.log)

**Comment by juanmanzanero** [comment]
Hello! I don't think this is the issue. Please try to copy the very first error you get, I'd be surprised if it the one you sent. Cheers

**Comment by dhr999** [comment]
Actually I did install using apt-get. I was able to build, Ipopt, CppAD,
TinyXml2 and other projects using the same canonical cmake steps. But I
fail to build lion.

**Comment by dhr999** [comment]
Hey I updated to gcc 9.4, using ```sudo apt install gcc-9```(and g++ 9.4 & gfortran-11) But now I get the following error msg(I deleted the previous build and did a fresh make)

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by juanmanzanero** [comment]
Superb! Thank you!

**Comment by dhr999** [comment]
I am still facing similar build issues for "fastest-lap". But I guess it's a separate issue, I will try to use my learning here.

Thanks a lot for your support. Hoping to contribute soon to the repo.
